### PR TITLE
Parallel

### PR DESCRIPTION
**Pull request by HershGupta404**
This adds an option to run code in parallel on multiple processes providing speedup. The number of procs can be specified from CLI and defaults to 4. 

Future Progress/Issues: 
- [ ] Progress is now out of order due to the way starmap chunks an iterable- need to think of a better way to keep track of progress, perhaps as percentage as opposed to actual count and use some heuristic to estimate. 
- [ ] Add support for other alteration events if this change is acceptable
- [x] Other bugs found while rewriting: GET requests fail when class property is not instantiated for Query objects- should I raise a separate ticket?

### CODE REVIEW

**Comment by HershGupta404** [comment]
@jjgao @zhx828 
Let me know if you need anything else or more comments on the changes I made

**Comment by zhx828** [comment]
> @jjgao @zhx828
> Let me know if you need anything else or more comments on the changes I made

Thank you for submitting the pull request! I will take a look this week and get back to you.

**Comment by zhx828** [comment]
@HershGupta404 thanks again for the effort. Here are few questions before taking a more detailed look at the pr
- why do you have a AnnotatorCore_parallel and MafAnnotator_parallel files?
- Is there a way to test the Parallel actually working? Can the test be included as part of pytest?
- Could you add a create an separate issue for the `GET requests` issue you mentioned?

**Comment by HershGupta404** [comment]
@zhx828 I think the parallel files should be deleted from commits 2-3. I updated the test file to work with the updated parallel code in commit 2. I can try to remove the parallel code from the commit history.

**Comment by zhx828** [comment]
@HershGupta404 will you work on this soon? Do you want me take over whatever is left?

**Comment by zhx828** [comment]
Gonna close this ticket since I haven't heard back from the user. Will reopen if situation changes.

**Pull request closed without merging**
