### PR TITLE
Use new annotate endpoints for different types of alteration

### PR DESCRIPTION
**Pull request by zhx828**
This solves https://github.com/oncokb/oncokb-annotator/issues/24
Signed-off-by: Hongxin Zhang <hongxin@lski1896.mskcc.org>

@jjgao this pr is ready to review, but let me do more testing before morning

### CODE REVIEW

**Comment by jjgao** [comment]
discussed on slack

- [ ] investigate the change for EGFR intragenic
- [ ] only pass Amplification and Deletion for CNA annotation
- [ ] per-variant comparison between old and new annotation

**Comment by zhx828** [comment]
@jjgao I've tested the msk-impact-2017. The result mostly looks identical except the intragenic fusion events. It turns out in the previous code, there is a bug that the intragenic format isn't converted to correct format(EGFR intragenic should be converted to EGFR-EGFR DELETION none functional fusion). It's getting all oncogenicity from Fusions. But in this pr it fixes the issue. It tries to get oncogenic event from Deletion, otherwise from Truncating Mutations if curated.

**Comment by jjgao** [comment]
Thanks, @zhx828 . Please merge this and release a new version?

**Comment by zhx828** [comment]
@jjgao going to increase the minor version.

**Pull request merged**
