### PR TITLE
Use POST methods for annotation to improve the performance

### PR DESCRIPTION
**Pull request by zhx828**
Tested in the msk_impact_2017 study. All annotation are the same.
This fixes https://github.com/oncokb/oncokb-annotator/issues/62

### CODE REVIEW

**Review by Leowisd — APPROVED** [review]

**Review by jjgao — COMMENTED** [review]
@zhx828 I am wondering if we need to more tests, e.g. adding some problematic rows (wrong gene for example) and see if the script can handle.

**Comment by zhx828** [comment]
@jjgao I added some fake gene tests

**Comment by jjgao** [comment]
Thanks, Hongxin. Have you tried it on the mskimpact cohort?

**Comment by zhx828** [comment]
> Thanks, Hongxin. Have you tried it on the mskimpact cohort?

I tested the msk_impact_2017. Didn't test on the internal. Figured that's too big to compare.

**Pull request merged**
